spring:
  kafka:
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    properties:
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:SCRAM-SHA-512}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
      ssl.truststore.type: PEM
      ssl.truststore.certificates: ${KAFKA_SSL_TRUSTSTORE_CERTIFICATES:}
      ssl.endpoint.identification.algorithm: ${KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:https}
