server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: ${SHUTDOWN_PHASE_TIMEOUT:25s}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${VIRTUALRIFT_RUNTIME_ENVIRONMENT:local}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,250ms,500ms,1s,2s,5s
  prometheus:
    metrics:
      export:
        enabled: true
